[id="chap-dashbuilder-deployment"]
== Deployment
ifdef::context[:parent-context: {context}]
:context: dashbuilder-essentials

[role="_abstract"]
Deploying dashboards for Dashbuilder is achieved by simply copying its static content to a web server or you can embed it in your application using an *iframe*.


=== Using Dashbuilder Web Application

Dashbuilder static content is published on NPM package https://www.npmjs.com/package/@kie-tools/dashbuilder-client[@kie-tools/dashbuilder-client]. You can add it a dependency for your project and then copy the static content to your application. 

For example, the following *package.json* will include Dashbuilder bits when using *npm run build* and allow users to run dashbuilder locally using *npm run server*

.package.json
[source]
----
{
  "name": "dashbuilder-webapp",
  "version": "0.0.0",
  "description": "Dashbuilder WebApp",
  "scripts": {
    "bootstrap": "npm install",
    "clean": "rm -rf dist/",
    "copy:dashbuilder": "cp -r node_modules/@kie-tools/dashbuilder-client/dist/* dist/",
    "copy:sources": "cp -r static/* dist",
    "build": "npm run clean && mkdir dist/ && npm run copy:dashbuilder && npm run copy:sources",
    "server": "npm run build && cd dist && http-server -p 8000"
  },
  "devDependencies": {
    "@kie-tools/dashbuilder-client": "^0.28.0",
    "http-server": "^14.1.1"
  }
}
----
In the directory `static` you should place your dashboards and the configuration file `setup.js`.


=== Configuration

In Dashbuilder webapp root directory there's a javaScript file `setup.js` where users can configure the list of dashboards, the mode (development or client) and samples.

.setup.js
[source]
----
dashbuilder = {
  /*
		  // possible modes are EDITOR and CLIENT - if dashboards is set then CLIENT mode is assumed
		  mode: "CLIENT",
		  // The list of client dashboards - if CLIENT mode is used and no list is provided, than the dashboard "dashboard.yml" will be attempted to load. If no dashboard is found, then client opens for upload. 
		  // The dashboard can also be an URL
		  dashboards: [ "dashboard1.yaml", "dashboard2.json"],
	  
		  // base path to look for dashboards. Default is /
		  path: "/path",
	  	
		  // if true, then model from external urls will be allowed
		  allowExternal: true,
	  	
		  // A base URL for the samples repository 
		  // if set then dashbuilder tries to retrieve samples.json from root dir and load samples from the provided URL
		  samplesUrl: "/samples",
	  	
		  // An URL to resolve sample path on disk. It will receive a GET request with a query parameter called "sampleId"
		  samplesEditService: "edit",
		  
		  // If true then samples is used as the default page when no model is selected
		  samplesDefaultHome: true
	  */
};
----

=== Cloud Deployment

From the https://start.kubesmarts.org/[online editor] you can deploy your dashboards to Openshift. This is explained on https://blog.kie.org/2022/08/deploying-dashbuilder-client-on-openshift-developer-sandbox.html[our blog]. 

Users can also create a https://blog.kie.org/2022/08/deploying-dashbuilder-client-on-openshift-developer-sandbox.html[custom image] to use with Dashbuilder static content. 

=== Loading content dinamically

Dashbuilder can run as an editor by simply setting the mode as `EDITOR`, then you can send content to be rendered using a global Javascript function `setDashbuilderContent` or use `window.postMessage` to the iframe where Dashbuilder is running. Here's a sample Javascript code:

[source]
----
// flag to indicate that dashbuilder is ready for content;
var ready = false;
window.addEventListener("message", (e) => {
  if (e.data === "ready") {
    ready = true;
  }
});

// Updates dashbuilder with the content (only if it is ready)
const send = () => {
    if (ready) {
        document.getElementById("dbFrame").contentWindow.postMessage(ymlContent, null);
    }
};
----